name: issues
on:
  issues:
    types: [opened, closed]
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Log issue event
        run: echo "Issue ${{ github.event.issue.number }} ${{ github.event.action }}"